### ISSUE TITLE
Recommended parameters for hg38?

### ISSUE THREAD

**Issue by davetang** [AnimaTardeb/G4Hunter#5]
What would be the recommended parameters (window size and score) for running `G4Hunter` on hg38?

**Comment by davetang** [comment]
I tried `-w 25` and `-s 1` but I got this error.

```
python G4Hunter.py -i hg38.fa -o hg38 -w 25 -s 1
25

         Re-evaluation of G-quadruplex propensity with G4Hunter 

#####################################
#    New Results directory Created  #
#####################################


 Input file: hg38
Traceback (most recent call last):
  File "G4Hunter.py", line 296, in <module>
    ScoreListe, DNASeq, NumListe, HeaderListe=soft1.GFinder(filein, window)
  File "G4Hunter.py", line 91, in GFinder
    Sequence,liste=self.BaseScore(ListSeq[i])
  File "G4Hunter.py", line 108, in BaseScore
    liste[item]=2
IndexError: list assignment index out of range
```

**Comment by AnimaTardeb** [comment]
Hey Dave. 
1-have you tried to run G4hunter on the genome provided (human mitochondrial genome)?
2- why there is 25 at the beginning of the second line of the code you provided?

**Comment by davetang** [comment]
Hey there.
1. Yup I can run `G4Hunter` on the provided FASTA file.
2. That's part of the output produced by `G4Hunter.py`.

My colleague told me that he fixed that problem by changing the code on line 107 from

```
if(item+1< len(line) and (line[item+1]=="G" or line[item+1]=="g")):
```

 to

```
if(item+1< len(line) and (line[item+1]=="G" or line[item+1]=="g") and item<len(liste)):
```

Is that OK?

**Comment by AnimaTardeb** [comment]
It might be a solution. 
However, a lot of people and I have ran this script on hg38 and HG37 without any modification 
the problem mostly is that there might be empty characters in the file 
I will let you know 

**Edit:**
item is just an index that goes from 0 to len(liste). 
I am wondering why only in this line you added "item<len(liste)"?  cause if it's a mandatory condition it should be in all the lines. 

I am afraid that this will change the score calculation and you will get false results. 

P.S. H.G. isa lil time consuming.

**Comment by AnimaTardeb** [comment]
I suggest you use w25 and s 1.5 if you want to screen the human genome

Bedrat Amina dlF.
https://github.com/AnimaTardeb/

**Comment by davetang** [comment]
Thank you for updating the code and for the recommendation. Just one more issue related to the output directory.

```bash
python G4Hunter.py -i chr22.fa -w 25 -s 1.5 -o tmp
Traceback (most recent call last):
  File "G4Hunter.py", line 277, in <module>
    OPF= os.listdir(outputfile)
OSError: [Errno 2] No such file or directory: 'tmp'

mkdir tmp
python G4Hunter.py -i chr22.fa -w 25 -s 1.5 -o tmp
Traceback (most recent call last):
  File "G4Hunter.py", line 292, in <module>
    os.makedirs(outputfile+"/"+DIR+"/", mode=0777)        #
NameError: name 'DIR' is not defined

mkdir tmp/Results_chr22
python G4Hunter.py -i chr22.fa -w 25 -s 1.5 -o tmp
true Results_chr22

         Re-evaluation of G-quadruplex propensity with G4Hunter 

#####################################
#    New Results directory Created  #
#####################################


 Input file: chr22

 Results files and Score Figure are created in:
tmp / Results_chr22 / 
```

**Comment by AnimaTardeb** [comment]
Last thing for the -o just indicate where you want to put the result directory. 
e.g. select PATH/TO/Document and the G4hunter will create result_nameoffile inside PATH/TO/Document/Result_nameoffile

1: if you are running different files separately you will have different folders each one has a name like : Result_nameoffile1 Result_nameoffile2 ...
`./G4hunter.py -i PATH/TO/FASTA -o PATH/TO/ALREADY/EXSITING/DIRECTORY -w 25 -s 1.5 `

**Comment by davetang** [comment]
Sorry, I thought the example was clear. You changed your code and it now looks for an output directory that is named: output directory + name of FASTA file without `.fa`. If that doesn't exist, the script will fail.

```bash
# output directory exists
mkdir tmp
python G4Hunter.py -i chr22.fa  -o tmp -w 25 -s 1.5
Traceback (most recent call last):
  File "G4Hunter.py", line 292, in <module>
    os.makedirs(outputfile+"/"+DIR+"/", mode=0777)        #
NameError: name 'DIR' is not defined
```

The script is looking for `Results_chr22` inside of tmp, which doesn't exist. If I manually create this, the script works.

```bash
mkdir -p tmp/Results_chr22
python G4Hunter.py -i chr22.fa  -o tmp -w 25 -s 1.5
# runs fine
```

**Comment by AnimaTardeb** [comment]
I still don't know why you need to create a directory. If it's a code error I have to correcte it.  

But first why are you working in your tmp folder ? 

Please see my console because I didn't need to create the result directory and I could erase it and recreate automatically. 

```console
$pwd
/Users/MYSH/G4Hunter-V4/G4Github
$ls
G4Hunter.py
$./G4Hunter.py -i /Users/MYSH/G4Hunter-V4/exemple/Mitochondri.fasta -o /Users/MYSH/G4Hunter-V4/G4Github -w 25 -s 1.5

########################################################################
#                            Results directory Created                 #
########################################################################


 Input file: Mitochondri

 Results files and Score Figure are created in:   
/Users/MYSH/G4Hunter-V4/G4Github / Results_Mitochondri / 
 
$ls
G4Hunter.py		Results_Mitochondri
$./G4Hunter.py -i /Users/MYSH/G4Hunter-V4/exemple/Mitochondri.fasta -o /Users/MYSH/G4Hunter-V4/G4Github -w 25 -s 1.5
true Results_Mitochondri

 	 Re-evaluation of G-quadruplex propensity with G4Hunter 

#####################################
#    New Results directory Created  #
#####################################


 Input file: Mitochondri

 Results files and Score Figure are created in:   
/Users/MYSH/G4Hunter-V4/G4Github / Results_Mitochondri / 
 
$ls
G4Hunter.py		Results_Mitochondri
$

```

**Comment by davetang** [comment]
Example from a fresh start.

```
pwd
/home/dtang/github

git clone https://github.com/AnimaTardeb/G4Hunter.git && cd G4Hunter

python ./G4Hunter.py -i Mitochondri.fasta -o ~/github/G4Hunter/ -w 25 -s 1.5

########################################################################
#                            Results directory Created                 #
########################################################################

Traceback (most recent call last):
  File "./G4Hunter.py", line 301, in <module>
    filein=open(inputfile,"r")
IOError: [Errno 2] No such file or directory: 'Mitochondri.fasta'
```

**Comment by AnimaTardeb** [comment]
In the folder downloaded there is no file named Mitochondri.fasta this is
why you are having the error.

The Fasta file is named  Mitochondria_NC_012920_1.fasta
<https://github.com/AnimaTardeb/G4Hunter/blob/master/Mitochondria_NC_012920_1.fasta>
.

Best

Bedrat Amina dlF.
https://github.com/AnimaTardeb/

**Comment by davetang** [comment]
Thank you for all your help.
